---
- name: Create temporary directory to store related files
  tempfile:
    state: directory
    suffix: portainer
  register: portainer_temp_dir
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Interpolate Ansible variables
  template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_temp_dir.path }}/docker-compose.yml"
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Deploy Portainer in Swarm
  command: 'docker stack deploy --compose-file {{ portainer_temp_dir.path }}/docker-compose.yml portainer'
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Record Traefik DNS
  ara_record:
    key: "portainer_host"
    value: "http://{{ portainer_host }}"
    type: url