version: '3'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - integr8
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000"
    volumes:
      - portainer_data:/data
    networks:
      - integr8
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.integr8.me
      - traefik.port=9000
      - traefik.docker.network=integr8
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  integr8:
    external: true

volumes:
  portainer_data:
